name: 'zuora_source'
version: '0.1.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]

vars:
  zuora_source:
    account: "{{ source('zuora', 'account') }}"
    contact: "{{ source('zuora', 'contact') }}"
    invoice: "{{ source('zuora', 'invoice') }}"
    order: "{{ source('zuora', 'order') }}"
    product: "{{ source('zuora', 'product') }}"
    subscription: "{{ source('zuora', 'subscription') }}"

  zuora_account_pass_through_columns: []
  zuora_subscription_pass_through_columns: []

models:
  dbt_zuora_source:
    +schema: zuora_source
    materialized: table
    tmp:
      materialized: view