name: 'zuora_source_integration_tests'
version: '0.1.0'
config-version: 2
profile: 'integration_tests'

vars:
  zuora_schema: zuora_source_integrations_tests
  zuora_source:
    zuora_account_identifier: "zuora_account_data"
    zuora_contact_identifier: "zuora_contact_data"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']