{% macro get_payment_columns() %}

{% set columns = [
    {"name": "_fivetran_deleted", "datatype": "boolean"},
    {"name": "_fivetran_synced", "datatype": dbt.type_timestamp()},
    {"name": "account_id", "datatype": dbt.type_string()},
    {"name": "accounting_code", "datatype": dbt.type_string()},
    {"name": "amount", "datatype": dbt.type_float()},
    {"name": "amount_currency_rounding", "datatype": dbt.type_float()},
    {"name": "amount_home_currency", "datatype": dbt.type_float()},
    {"name": "applied_amount", "datatype": dbt.type_float()},
    {"name": "applied_credit_balance_amount", "datatype": dbt.type_float()},
    {"name": "auth_transaction_id", "datatype": dbt.type_string()},
    {"name": "bank_identification_number", "datatype": dbt.type_string()},
    {"name": "bill_to_contact_id", "datatype": dbt.type_string()},
    {"name": "cancelled_on", "datatype": dbt.type_timestamp()},
    {"name": "comment", "datatype": dbt.type_string()},
    {"name": "created_by_id", "datatype": dbt.type_string()},
    {"name": "created_date", "datatype": dbt.type_timestamp()},
    {"name": "currency", "datatype": dbt.type_string()},
    {"name": "default_payment_method_id", "datatype": dbt.type_string()},
    {"name": "effective_date", "datatype": "date"},
    {"name": "exchange_rate", "datatype": dbt.type_float()},
    {"name": "exchange_rate_date", "datatype": "date"},
    {"name": "gateway", "datatype": dbt.type_string()},
    {"name": "gateway_order_id", "datatype": dbt.type_string()},
    {"name": "gateway_reconciliation_reason", "datatype": dbt.type_string()},
    {"name": "gateway_reconciliation_status", "datatype": dbt.type_string()},
    {"name": "gateway_response", "datatype": dbt.type_string()},
    {"name": "gateway_response_code", "datatype": dbt.type_string()},
    {"name": "gateway_state", "datatype": dbt.type_string()},
    {"name": "home_currency", "datatype": dbt.type_string()},
    {"name": "id", "datatype": dbt.type_string()},
    {"name": "is_standalone", "datatype": "boolean"},
    {"name": "marked_for_submission_on", "datatype": dbt.type_timestamp()},
    {"name": "parent_account_id", "datatype": dbt.type_string()},
    {"name": "payment_method_id", "datatype": dbt.type_string()},
    {"name": "payment_number", "datatype": dbt.type_string()},
    {"name": "payout_id", "datatype": dbt.type_string()},
    {"name": "provider_exchange_rate_date", "datatype": "date"},
    {"name": "reference_id", "datatype": dbt.type_string()},
    {"name": "referenced_payment_id", "datatype": dbt.type_string()},
    {"name": "refund_amount", "datatype": dbt.type_float()},
    {"name": "second_payment_reference_id", "datatype": dbt.type_string()},
    {"name": "settled_on", "datatype": dbt.type_timestamp()},
    {"name": "soft_descriptor", "datatype": dbt.type_string()},
    {"name": "soft_descriptor_phone", "datatype": dbt.type_string()},
    {"name": "sold_to_contact_id", "datatype": dbt.type_string()},
    {"name": "source", "datatype": dbt.type_string()},
    {"name": "source_name", "datatype": dbt.type_string()},
    {"name": "status", "datatype": dbt.type_string()},
    {"name": "submitted_on", "datatype": dbt.type_timestamp()},
    {"name": "transaction_currency", "datatype": dbt.type_string()},
    {"name": "transferred_to_accounting", "datatype": dbt.type_string()},
    {"name": "type", "datatype": dbt.type_string()},
    {"name": "unapplied_amount", "datatype": dbt.type_float()},
    {"name": "updated_by_id", "datatype": dbt.type_string()},
    {"name": "updated_date", "datatype": dbt.type_timestamp()}
] %}

{{ return(columns) }}

{% endmacro %}
