
with base as (

    select * 
    from {{ ref('stg_zuora__rate_plan_charge_tmp') }}
),

fields as (

    select
        {{
            fivetran_utils.fill_staging_columns(
                source_columns=adapter.get_columns_in_relation(ref('stg_zuora__rate_plan_charge_tmp')),
                staging_columns=get_rate_plan_charge_columns()
            )
        }}
    from base
),

final as (
    
    select 
        id as rate_plan_charge_id,
        _fivetran_deleted,
        _fivetran_synced,
        account_id,
        account_receivable_accounting_code_id,
        accounting_code,
        amended_by_order_on,
        amendment_id,
        apply_discount_to,
        bill_cycle_day,
        bill_cycle_type,
        bill_to_contact_id,
        bill_to_contact_snapshot_id,
        billing_period,
        billing_period_alignment,
        billing_timing,
        booking_exchange_rate,
        booking_exchange_rate_date,
        booking_provider_exchange_rate_date,
        charge_model,
        charge_number,
        charge_type,
        charged_through_date,
        created_by_id,
        created_date,
        credit_option,
        default_payment_method_id,
        deferred_revenue_accounting_code_id,
        description,
        discount_level,
        dmrc,
        dmrccurrency_rounding,
        dmrchome_currency,
        drawdown_rate,
        drawdown_uom,
        dtcv,
        dtcvcurrency_rounding,
        dtcvhome_currency,
        effective_end_date,
        effective_start_date,
        end_date_condition,
        exchange_rate,
        exchange_rate_date,
        exclude_item_billing_from_revenue_accounting,
        exclude_item_booking_from_revenue_accounting,
        home_currency,
        invoice_owner_id,
        is_last_segment,
        is_prepaid,
        is_processed,
        is_rollover,
        list_price_base,
        mrr,
        mrrcurrency_rounding,
        mrrhome_currency,
        name,
        number_of_periods,
        original_id,
        original_order_date,
        overage_calculation_option,
        overage_unused_units_credit_option,
        parent_account_id,
        payment_term_snapshot,
        prepaid_operation_type,
        prepaid_quantity,
        prepaid_total_quantity,
        prepaid_uom,
        price_change_option,
        price_increase_percentage,
        processed_through_date,
        product_id,
        product_rate_plan_charge_id,
        product_rate_plan_id,
        provider_exchange_rate_date,
        quantity,
        rate_plan_id,
        rating_group,
        recognized_revenue_accounting_code_id,
        rev_rec_code,
        rev_rec_trigger_condition,
        revenue_recognition_rule_name,
        rollover_apply,
        rollover_periods,
        segment,
        sold_to_contact_id,
        sold_to_contact_snapshot_id,
        specific_billing_period,
        specific_end_date,
        specific_list_price_base,
        subscription_id,
        subscription_owner_id,
        tcv,
        tcvcurrency_rounding,
        tcvhome_currency,
        transaction_currency,
        trigger_date,
        trigger_event,
        uom,
        up_to_periods,
        up_to_periods_type,
        updated_by_id,
        updated_date,
        validity_period_type,
        version,
        weekly_bill_cycle_day
    from fields
)

select *
from final
